import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import AddressDistrict from 'App/Models/AddressDistrict'

export default class extends BaseSeeder {
  public async run () {
    // Write your database queries inside the run method
    await AddressDistrict.createMany([
      {"districtId":"1","provinceId":"1","name":"Quận Ba Đình"},
      {"districtId":"2","provinceId":"1","name":"Quận Hoàn Kiếm"},
      {"districtId":"3","provinceId":"1","name":"Quận Tây Hồ"},
      {"districtId":"4","provinceId":"1","name":"Quận Long Biên"},
      {"districtId":"5","provinceId":"1","name":"Quận Cầu Giấy"},
      {"districtId":"6","provinceId":"1","name":"Quận Đống Đa"},
      {"districtId":"7","provinceId":"1","name":"Quận Hai Bà Trưng"},
      {"districtId":"8","provinceId":"1","name":"Quận Hoàng Mai"},
      {"districtId":"9","provinceId":"1","name":"Quận Thanh Xuân"},
      {"districtId":"10","provinceId":"1","name":"Huyện Sóc Sơn"},
      {"districtId":"11","provinceId":"1","name":"Huyện Đông Anh"},
      {"districtId":"12","provinceId":"1","name":"Huyện Gia Lâm"},
      {"districtId":"13","provinceId":"1","name":"Quận Nam Từ Liêm"},
      {"districtId":"14","provinceId":"1","name":"Huyện Thanh Trì"},
      {"districtId":"15","provinceId":"1","name":"Quận Bắc Từ Liêm"},
      {"districtId":"16","provinceId":"1","name":"Huyện Mê Linh"},
      {"districtId":"17","provinceId":"1","name":"Quận Hà Đông"},
      {"districtId":"18","provinceId":"1","name":"Thị xã Sơn Tây"},
      {"districtId":"19","provinceId":"1","name":"Huyện Ba Vì"},
      {"districtId":"20","provinceId":"1","name":"Huyện Phúc Thọ"},
      {"districtId":"21","provinceId":"1","name":"Huyện Đan Phượng"},
      {"districtId":"22","provinceId":"1","name":"Huyện Hoài Đức"},
      {"districtId":"23","provinceId":"1","name":"Huyện Quốc Oai"},
      {"districtId":"24","provinceId":"1","name":"Huyện Thạch Thất"},
      {"districtId":"25","provinceId":"1","name":"Huyện Chương Mỹ"},
      {"districtId":"26","provinceId":"1","name":"Huyện Thanh Oai"},
      {"districtId":"27","provinceId":"1","name":"Huyện Thường Tín"},
      {"districtId":"28","provinceId":"1","name":"Huyện Phú Xuyên"},
      {"districtId":"29","provinceId":"1","name":"Huyện Ứng Hòa"},
      {"districtId":"30","provinceId":"1","name":"Huyện Mỹ Đức"},
      {"districtId":"31","provinceId":"2","name":"Thành phố Hà Giang"},
      {"districtId":"32","provinceId":"2","name":"Huyện Đồng Văn"},
      {"districtId":"33","provinceId":"2","name":"Huyện Mèo Vạc"},
      {"districtId":"34","provinceId":"2","name":"Huyện Yên Minh"},
      {"districtId":"35","provinceId":"2","name":"Huyện Quản Bạ"},
      {"districtId":"36","provinceId":"2","name":"Huyện Vị Xuyên"},
      {"districtId":"37","provinceId":"2","name":"Huyện Bắc Mê"},
      {"districtId":"38","provinceId":"2","name":"Huyện Hoàng Su Phì"},
      {"districtId":"39","provinceId":"2","name":"Huyện Xín Mần"},
      {"districtId":"40","provinceId":"2","name":"Huyện Bắc Quang"},
      {"districtId":"41","provinceId":"2","name":"Huyện Quang Bình"},
      {"districtId":"42","provinceId":"3","name":"Thành phố Cao Bằng"},
      {"districtId":"43","provinceId":"3","name":"Huyện Bảo Lâm"},
      {"districtId":"44","provinceId":"3","name":"Huyện Bảo Lạc"},
      {"districtId":"45","provinceId":"3","name":"Huyện Hà Quảng"},
      {"districtId":"46","provinceId":"3","name":"Huyện Trùng Khánh"},
      {"districtId":"47","provinceId":"3","name":"Huyện Hạ Lang"},
      {"districtId":"48","provinceId":"3","name":"Huyện Quảng Hòa"},
      {"districtId":"49","provinceId":"3","name":"Huyện Hoà An"},
      {"districtId":"50","provinceId":"3","name":"Huyện Nguyên Bình"},
      {"districtId":"51","provinceId":"3","name":"Huyện Thạch An"},
      {"districtId":"52","provinceId":"4","name":"Thành Phố Bắc Kạn"},
      {"districtId":"53","provinceId":"4","name":"Huyện Pác Nặm"},
      {"districtId":"54","provinceId":"4","name":"Huyện Ba Bể"},
      {"districtId":"55","provinceId":"4","name":"Huyện Ngân Sơn"},
      {"districtId":"56","provinceId":"4","name":"Huyện Bạch Thông"},
      {"districtId":"57","provinceId":"4","name":"Huyện Chợ Đồn"},
      {"districtId":"58","provinceId":"4","name":"Huyện Chợ Mới"},
      {"districtId":"59","provinceId":"4","name":"Huyện Na Rì"},
      {"districtId":"60","provinceId":"5","name":"Thành phố Tuyên Quang"},
      {"districtId":"61","provinceId":"5","name":"Huyện Lâm Bình"},
      {"districtId":"62","provinceId":"5","name":"Huyện Na Hang"},
      {"districtId":"63","provinceId":"5","name":"Huyện Chiêm Hóa"},
      {"districtId":"64","provinceId":"5","name":"Huyện Hàm Yên"},
      {"districtId":"65","provinceId":"5","name":"Huyện Yên Sơn"},
      {"districtId":"66","provinceId":"5","name":"Huyện Sơn Dương"},
      {"districtId":"67","provinceId":"6","name":"Thành phố Lào Cai"},
      {"districtId":"68","provinceId":"6","name":"Huyện Bát Xát"},
      {"districtId":"69","provinceId":"6","name":"Huyện Mường Khương"},
      {"districtId":"70","provinceId":"6","name":"Huyện Si Ma Cai"},
      {"districtId":"71","provinceId":"6","name":"Huyện Bắc Hà"},
      {"districtId":"72","provinceId":"6","name":"Huyện Bảo Thắng"},
      {"districtId":"73","provinceId":"6","name":"Huyện Bảo Yên"},
      {"districtId":"74","provinceId":"6","name":"Thị xã Sa Pa"},
      {"districtId":"75","provinceId":"6","name":"Huyện Văn Bàn"},
      {"districtId":"76","provinceId":"7","name":"Thành phố Điện Biên Phủ"},
      {"districtId":"77","provinceId":"7","name":"Thị Xã Mường Lay"},
      {"districtId":"78","provinceId":"7","name":"Huyện Mường Nhé"},
      {"districtId":"79","provinceId":"7","name":"Huyện Mường Chà"},
      {"districtId":"80","provinceId":"7","name":"Huyện Tủa Chùa"},
      {"districtId":"81","provinceId":"7","name":"Huyện Tuần Giáo"},
      {"districtId":"82","provinceId":"7","name":"Huyện Điện Biên"},
      {"districtId":"83","provinceId":"7","name":"Huyện Điện Biên Đông"},
      {"districtId":"84","provinceId":"7","name":"Huyện Mường Ảng"},
      {"districtId":"85","provinceId":"7","name":"Huyện Nậm Pồ"},
      {"districtId":"86","provinceId":"8","name":"Thành phố Lai Châu"},
      {"districtId":"87","provinceId":"8","name":"Huyện Tam Đường"},
      {"districtId":"88","provinceId":"8","name":"Huyện Mường Tè"},
      {"districtId":"89","provinceId":"8","name":"Huyện Sìn Hồ"},
      {"districtId":"90","provinceId":"8","name":"Huyện Phong Thổ"},
      {"districtId":"91","provinceId":"8","name":"Huyện Than Uyên"},
      {"districtId":"92","provinceId":"8","name":"Huyện Tân Uyên"},
      {"districtId":"93","provinceId":"8","name":"Huyện Nậm Nhùn"},
      {"districtId":"94","provinceId":"9","name":"Thành phố Sơn La"},
      {"districtId":"95","provinceId":"9","name":"Huyện Quỳnh Nhai"},
      {"districtId":"96","provinceId":"9","name":"Huyện Thuận Châu"},
      {"districtId":"97","provinceId":"9","name":"Huyện Mường La"},
      {"districtId":"98","provinceId":"9","name":"Huyện Bắc Yên"},
      {"districtId":"99","provinceId":"9","name":"Huyện Phù Yên"},
      {"districtId":"100","provinceId":"9","name":"Huyện Mộc Châu"},
      {"districtId":"101","provinceId":"9","name":"Huyện Yên Châu"},
      {"districtId":"102","provinceId":"9","name":"Huyện Mai Sơn"},
      {"districtId":"103","provinceId":"9","name":"Huyện Sông Mã"},
      {"districtId":"104","provinceId":"9","name":"Huyện Sốp Cộp"},
      {"districtId":"105","provinceId":"9","name":"Huyện Vân Hồ"},
      {"districtId":"106","provinceId":"10","name":"Thành phố Yên Bái"},
      {"districtId":"107","provinceId":"10","name":"Thị xã Nghĩa Lộ"},
      {"districtId":"108","provinceId":"10","name":"Huyện Lục Yên"},
      {"districtId":"109","provinceId":"10","name":"Huyện Văn Yên"},
      {"districtId":"110","provinceId":"10","name":"Huyện Mù Căng Chải"},
      {"districtId":"111","provinceId":"10","name":"Huyện Trấn Yên"},
      {"districtId":"112","provinceId":"10","name":"Huyện Trạm Tấu"},
      {"districtId":"113","provinceId":"10","name":"Huyện Văn Chấn"},
      {"districtId":"114","provinceId":"10","name":"Huyện Yên Bình"},
      {"districtId":"115","provinceId":"11","name":"Thành phố Hòa Bình"},
      {"districtId":"116","provinceId":"11","name":"Huyện Đà Bắc"},
      {"districtId":"117","provinceId":"11","name":"Huyện Lương Sơn"},
      {"districtId":"118","provinceId":"11","name":"Huyện Kim Bôi"},
      {"districtId":"119","provinceId":"11","name":"Huyện Cao Phong"},
      {"districtId":"120","provinceId":"11","name":"Huyện Tân Lạc"},
      {"districtId":"121","provinceId":"11","name":"Huyện Mai Châu"},
      {"districtId":"122","provinceId":"11","name":"Huyện Lạc Sơn"},
      {"districtId":"123","provinceId":"11","name":"Huyện Yên Thủy"},
      {"districtId":"124","provinceId":"11","name":"Huyện Lạc Thủy"},
      {"districtId":"125","provinceId":"12","name":"Thành phố Thái Nguyên"},
      {"districtId":"126","provinceId":"12","name":"Thành phố Sông Công"},
      {"districtId":"127","provinceId":"12","name":"Huyện Định Hóa"},
      {"districtId":"128","provinceId":"12","name":"Huyện Phú Lương"},
      {"districtId":"129","provinceId":"12","name":"Huyện Đồng Hỷ"},
      {"districtId":"130","provinceId":"12","name":"Huyện Võ Nhai"},
      {"districtId":"131","provinceId":"12","name":"Huyện Đại Từ"},
      {"districtId":"132","provinceId":"12","name":"Thị xã Phổ Yên"},
      {"districtId":"133","provinceId":"12","name":"Huyện Phú Bình"},
      {"districtId":"134","provinceId":"13","name":"Thành phố Lạng Sơn"},
      {"districtId":"135","provinceId":"13","name":"Huyện Tràng Định"},
      {"districtId":"136","provinceId":"13","name":"Huyện Bình Gia"},
      {"districtId":"137","provinceId":"13","name":"Huyện Văn Lãng"},
      {"districtId":"138","provinceId":"13","name":"Huyện Cao Lộc"},
      {"districtId":"139","provinceId":"13","name":"Huyện Văn Quan"},
      {"districtId":"140","provinceId":"13","name":"Huyện Bắc Sơn"},
      {"districtId":"141","provinceId":"13","name":"Huyện Hữu Lũng"},
      {"districtId":"142","provinceId":"13","name":"Huyện Chi Lăng"},
      {"districtId":"143","provinceId":"13","name":"Huyện Lộc Bình"},
      {"districtId":"144","provinceId":"13","name":"Huyện Đình Lập"},
      {"districtId":"145","provinceId":"14","name":"Thành phố Hạ Long"},
      {"districtId":"146","provinceId":"14","name":"Thành phố Móng Cái"},
      {"districtId":"147","provinceId":"14","name":"Thành phố Cẩm Phả"},
      {"districtId":"148","provinceId":"14","name":"Thành phố Uông Bí"},
      {"districtId":"149","provinceId":"14","name":"Huyện Bình Liêu"},
      {"districtId":"150","provinceId":"14","name":"Huyện Tiên Yên"},
      {"districtId":"151","provinceId":"14","name":"Huyện Đầm Hà"},
      {"districtId":"152","provinceId":"14","name":"Huyện Hải Hà"},
      {"districtId":"153","provinceId":"14","name":"Huyện Ba Chẽ"},
      {"districtId":"154","provinceId":"14","name":"Huyện Vân Đồn"},
      {"districtId":"155","provinceId":"14","name":"Thị xã Đông Triều"},
      {"districtId":"156","provinceId":"14","name":"Thị xã Quảng Yên"},
      {"districtId":"157","provinceId":"14","name":"Huyện Cô Tô"},
      {"districtId":"158","provinceId":"15","name":"Thành phố Bắc Giang"},
      {"districtId":"159","provinceId":"15","name":"Huyện Yên Thế"},
      {"districtId":"160","provinceId":"15","name":"Huyện Tân Yên"},
      {"districtId":"161","provinceId":"15","name":"Huyện Lạng Giang"},
      {"districtId":"162","provinceId":"15","name":"Huyện Lục Nam"},
      {"districtId":"163","provinceId":"15","name":"Huyện Lục Ngạn"},
      {"districtId":"164","provinceId":"15","name":"Huyện Sơn Động"},
      {"districtId":"165","provinceId":"15","name":"Huyện Yên Dũng"},
      {"districtId":"166","provinceId":"15","name":"Huyện Việt Yên"},
      {"districtId":"167","provinceId":"15","name":"Huyện Hiệp Hòa"},
      {"districtId":"168","provinceId":"16","name":"Thành phố Việt Trì"},
      {"districtId":"169","provinceId":"16","name":"Thị xã Phú Thọ"},
      {"districtId":"170","provinceId":"16","name":"Huyện Đoan Hùng"},
      {"districtId":"171","provinceId":"16","name":"Huyện Hạ Hoà"},
      {"districtId":"172","provinceId":"16","name":"Huyện Thanh Ba"},
      {"districtId":"173","provinceId":"16","name":"Huyện Phù Ninh"},
      {"districtId":"174","provinceId":"16","name":"Huyện Yên Lập"},
      {"districtId":"175","provinceId":"16","name":"Huyện Cẩm Khê"},
      {"districtId":"176","provinceId":"16","name":"Huyện Tam Nông"},
      {"districtId":"177","provinceId":"16","name":"Huyện Lâm Thao"},
      {"districtId":"178","provinceId":"16","name":"Huyện Thanh Sơn"},
      {"districtId":"179","provinceId":"16","name":"Huyện Thanh Thuỷ"},
      {"districtId":"180","provinceId":"16","name":"Huyện Tân Sơn"},
      {"districtId":"181","provinceId":"17","name":"Thành phố Vĩnh Yên"},
      {"districtId":"182","provinceId":"17","name":"Thành phố Phúc Yên"},
      {"districtId":"183","provinceId":"17","name":"Huyện Lập Thạch"},
      {"districtId":"184","provinceId":"17","name":"Huyện Tam Dương"},
      {"districtId":"185","provinceId":"17","name":"Huyện Tam Đảo"},
      {"districtId":"186","provinceId":"17","name":"Huyện Bình Xuyên"},
      {"districtId":"187","provinceId":"17","name":"Huyện Yên Lạc"},
      {"districtId":"188","provinceId":"17","name":"Huyện Vĩnh Tường"},
      {"districtId":"189","provinceId":"17","name":"Huyện Sông Lô"},
      {"districtId":"190","provinceId":"18","name":"Thành phố Bắc Ninh"},
      {"districtId":"191","provinceId":"18","name":"Huyện Yên Phong"},
      {"districtId":"192","provinceId":"18","name":"Huyện Quế Võ"},
      {"districtId":"193","provinceId":"18","name":"Huyện Tiên Du"},
      {"districtId":"194","provinceId":"18","name":"Thành phố Từ Sơn"},
      {"districtId":"195","provinceId":"18","name":"Huyện Thuận Thành"},
      {"districtId":"196","provinceId":"18","name":"Huyện Gia Bình"},
      {"districtId":"197","provinceId":"18","name":"Huyện Lương Tài"},
      {"districtId":"198","provinceId":"19","name":"Thành phố Hải Dương"},
      {"districtId":"199","provinceId":"19","name":"Thành phố Chí Linh"},
      {"districtId":"200","provinceId":"19","name":"Huyện Nam Sách"},
      {"districtId":"201","provinceId":"19","name":"Thị xã Kinh Môn"},
      {"districtId":"202","provinceId":"19","name":"Huyện Kim Thành"},
      {"districtId":"203","provinceId":"19","name":"Huyện Thanh Hà"},
      {"districtId":"204","provinceId":"19","name":"Huyện Cẩm Giàng"},
      {"districtId":"205","provinceId":"19","name":"Huyện Bình Giang"},
      {"districtId":"206","provinceId":"19","name":"Huyện Gia Lộc"},
      {"districtId":"207","provinceId":"19","name":"Huyện Tứ Kỳ"},
      {"districtId":"208","provinceId":"19","name":"Huyện Ninh Giang"},
      {"districtId":"209","provinceId":"19","name":"Huyện Thanh Miện"},
      {"districtId":"210","provinceId":"20","name":"Quận Hồng Bàng"},
      {"districtId":"211","provinceId":"20","name":"Quận Ngô Quyền"},
      {"districtId":"212","provinceId":"20","name":"Quận Lê Chân"},
      {"districtId":"213","provinceId":"20","name":"Quận Hải An"},
      {"districtId":"214","provinceId":"20","name":"Quận Kiến An"},
      {"districtId":"215","provinceId":"20","name":"Quận Đồ Sơn"},
      {"districtId":"216","provinceId":"20","name":"Quận Dương Kinh"},
      {"districtId":"217","provinceId":"20","name":"Huyện Thuỷ Nguyên"},
      {"districtId":"218","provinceId":"20","name":"Huyện An Dương"},
      {"districtId":"219","provinceId":"20","name":"Huyện An Lão"},
      {"districtId":"220","provinceId":"20","name":"Huyện Kiến Thuỵ"},
      {"districtId":"221","provinceId":"20","name":"Huyện Tiên Lãng"},
      {"districtId":"222","provinceId":"20","name":"Huyện Vĩnh Bảo"},
      {"districtId":"223","provinceId":"20","name":"Huyện Cát Hải"},
      {"districtId":"224","provinceId":"20","name":"Huyện Bạch Long Vĩ"},
      {"districtId":"225","provinceId":"21","name":"Thành phố Hưng Yên"},
      {"districtId":"226","provinceId":"21","name":"Huyện Văn Lâm"},
      {"districtId":"227","provinceId":"21","name":"Huyện Văn Giang"},
      {"districtId":"228","provinceId":"21","name":"Huyện Yên Mỹ"},
      {"districtId":"229","provinceId":"21","name":"Thị xã Mỹ Hào"},
      {"districtId":"230","provinceId":"21","name":"Huyện Ân Thi"},
      {"districtId":"231","provinceId":"21","name":"Huyện Khoái Châu"},
      {"districtId":"232","provinceId":"21","name":"Huyện Kim Động"},
      {"districtId":"233","provinceId":"21","name":"Huyện Tiên Lữ"},
      {"districtId":"234","provinceId":"21","name":"Huyện Phù Cừ"},
      {"districtId":"235","provinceId":"22","name":"Thành phố Thái Bình"},
      {"districtId":"236","provinceId":"22","name":"Huyện Quỳnh Phụ"},
      {"districtId":"237","provinceId":"22","name":"Huyện Hưng Hà"},
      {"districtId":"238","provinceId":"22","name":"Huyện Đông Hưng"},
      {"districtId":"239","provinceId":"22","name":"Huyện Thái Thụy"},
      {"districtId":"240","provinceId":"22","name":"Huyện Tiền Hải"},
      {"districtId":"241","provinceId":"22","name":"Huyện Kiến Xương"},
      {"districtId":"242","provinceId":"22","name":"Huyện Vũ Thư"},
      {"districtId":"243","provinceId":"23","name":"Thành phố Phủ Lý"},
      {"districtId":"244","provinceId":"23","name":"Thị xã Duy Tiên"},
      {"districtId":"245","provinceId":"23","name":"Huyện Kim Bảng"},
      {"districtId":"246","provinceId":"23","name":"Huyện Thanh Liêm"},
      {"districtId":"247","provinceId":"23","name":"Huyện Bình Lục"},
      {"districtId":"248","provinceId":"23","name":"Huyện Lý Nhân"},
      {"districtId":"249","provinceId":"24","name":"Thành phố Nam Định"},
      {"districtId":"250","provinceId":"24","name":"Huyện Mỹ Lộc"},
      {"districtId":"251","provinceId":"24","name":"Huyện Vụ Bản"},
      {"districtId":"252","provinceId":"24","name":"Huyện Ý Yên"},
      {"districtId":"253","provinceId":"24","name":"Huyện Nghĩa Hưng"},
      {"districtId":"254","provinceId":"24","name":"Huyện Nam Trực"},
      {"districtId":"255","provinceId":"24","name":"Huyện Trực Ninh"},
      {"districtId":"256","provinceId":"24","name":"Huyện Xuân Trường"},
      {"districtId":"257","provinceId":"24","name":"Huyện Giao Thủy"},
      {"districtId":"258","provinceId":"24","name":"Huyện Hải Hậu"},
      {"districtId":"259","provinceId":"25","name":"Thành phố Ninh Bình"},
      {"districtId":"260","provinceId":"25","name":"Thành phố Tam Điệp"},
      {"districtId":"261","provinceId":"25","name":"Huyện Nho Quan"},
      {"districtId":"262","provinceId":"25","name":"Huyện Gia Viễn"},
      {"districtId":"263","provinceId":"25","name":"Huyện Hoa Lư"},
      {"districtId":"264","provinceId":"25","name":"Huyện Yên Khánh"},
      {"districtId":"265","provinceId":"25","name":"Huyện Kim Sơn"},
      {"districtId":"266","provinceId":"25","name":"Huyện Yên Mô"},
      {"districtId":"267","provinceId":"26","name":"Thành phố Thanh Hóa"},
      {"districtId":"268","provinceId":"26","name":"Thị xã Bỉm Sơn"},
      {"districtId":"269","provinceId":"26","name":"Thành phố Sầm Sơn"},
      {"districtId":"270","provinceId":"26","name":"Huyện Mường Lát"},
      {"districtId":"271","provinceId":"26","name":"Huyện Quan Hóa"},
      {"districtId":"272","provinceId":"26","name":"Huyện Bá Thước"},
      {"districtId":"273","provinceId":"26","name":"Huyện Quan Sơn"},
      {"districtId":"274","provinceId":"26","name":"Huyện Lang Chánh"},
      {"districtId":"275","provinceId":"26","name":"Huyện Ngọc Lặc"},
      {"districtId":"276","provinceId":"26","name":"Huyện Cẩm Thủy"},
      {"districtId":"277","provinceId":"26","name":"Huyện Thạch Thành"},
      {"districtId":"278","provinceId":"26","name":"Huyện Hà Trung"},
      {"districtId":"279","provinceId":"26","name":"Huyện Vĩnh Lộc"},
      {"districtId":"280","provinceId":"26","name":"Huyện Yên Định"},
      {"districtId":"281","provinceId":"26","name":"Huyện Thọ Xuân"},
      {"districtId":"282","provinceId":"26","name":"Huyện Thường Xuân"},
      {"districtId":"283","provinceId":"26","name":"Huyện Triệu Sơn"},
      {"districtId":"284","provinceId":"26","name":"Huyện Thiệu Hóa"},
      {"districtId":"285","provinceId":"26","name":"Huyện Hoằng Hóa"},
      {"districtId":"286","provinceId":"26","name":"Huyện Hậu Lộc"},
      {"districtId":"287","provinceId":"26","name":"Huyện Nga Sơn"},
      {"districtId":"288","provinceId":"26","name":"Huyện Như Xuân"},
      {"districtId":"289","provinceId":"26","name":"Huyện Như Thanh"},
      {"districtId":"290","provinceId":"26","name":"Huyện Nông Cống"},
      {"districtId":"291","provinceId":"26","name":"Huyện Đông Sơn"},
      {"districtId":"292","provinceId":"26","name":"Huyện Quảng Xương"},
      {"districtId":"293","provinceId":"26","name":"Thị xã Nghi Sơn"},
      {"districtId":"294","provinceId":"27","name":"Thành phố Vinh"},
      {"districtId":"295","provinceId":"27","name":"Thị xã Cửa Lò"},
      {"districtId":"296","provinceId":"27","name":"Thị xã Thái Hoà"},
      {"districtId":"297","provinceId":"27","name":"Huyện Quế Phong"},
      {"districtId":"298","provinceId":"27","name":"Huyện Quỳ Châu"},
      {"districtId":"299","provinceId":"27","name":"Huyện Kỳ Sơn"},
      {"districtId":"300","provinceId":"27","name":"Huyện Tương Dương"},
      {"districtId":"301","provinceId":"27","name":"Huyện Nghĩa Đàn"},
      {"districtId":"302","provinceId":"27","name":"Huyện Quỳ Hợp"},
      {"districtId":"303","provinceId":"27","name":"Huyện Quỳnh Lưu"},
      {"districtId":"304","provinceId":"27","name":"Huyện Con Cuông"},
      {"districtId":"305","provinceId":"27","name":"Huyện Tân Kỳ"},
      {"districtId":"306","provinceId":"27","name":"Huyện Anh Sơn"},
      {"districtId":"307","provinceId":"27","name":"Huyện Diễn Châu"},
      {"districtId":"308","provinceId":"27","name":"Huyện Yên Thành"},
      {"districtId":"309","provinceId":"27","name":"Huyện Đô Lương"},
      {"districtId":"310","provinceId":"27","name":"Huyện Thanh Chương"},
      {"districtId":"311","provinceId":"27","name":"Huyện Nghi Lộc"},
      {"districtId":"312","provinceId":"27","name":"Huyện Nam Đàn"},
      {"districtId":"313","provinceId":"27","name":"Huyện Hưng Nguyên"},
      {"districtId":"314","provinceId":"27","name":"Thị xã Hoàng Mai"},
      {"districtId":"315","provinceId":"28","name":"Thành phố Hà Tĩnh"},
      {"districtId":"316","provinceId":"28","name":"Thị xã Hồng Lĩnh"},
      {"districtId":"317","provinceId":"28","name":"Huyện Hương Sơn"},
      {"districtId":"318","provinceId":"28","name":"Huyện Đức Thọ"},
      {"districtId":"319","provinceId":"28","name":"Huyện Vũ Quang"},
      {"districtId":"320","provinceId":"28","name":"Huyện Nghi Xuân"},
      {"districtId":"321","provinceId":"28","name":"Huyện Can Lộc"},
      {"districtId":"322","provinceId":"28","name":"Huyện Hương Khê"},
      {"districtId":"323","provinceId":"28","name":"Huyện Thạch Hà"},
      {"districtId":"324","provinceId":"28","name":"Huyện Cẩm Xuyên"},
      {"districtId":"325","provinceId":"28","name":"Huyện Kỳ Anh"},
      {"districtId":"326","provinceId":"28","name":"Huyện Lộc Hà"},
      {"districtId":"327","provinceId":"28","name":"Thị xã Kỳ Anh"},
      {"districtId":"328","provinceId":"29","name":"Thành Phố Đồng Hới"},
      {"districtId":"329","provinceId":"29","name":"Huyện Minh Hóa"},
      {"districtId":"330","provinceId":"29","name":"Huyện Tuyên Hóa"},
      {"districtId":"331","provinceId":"29","name":"Huyện Quảng Trạch"},
      {"districtId":"332","provinceId":"29","name":"Huyện Bố Trạch"},
      {"districtId":"333","provinceId":"29","name":"Huyện Quảng Ninh"},
      {"districtId":"334","provinceId":"29","name":"Huyện Lệ Thủy"},
      {"districtId":"335","provinceId":"29","name":"Thị xã Ba Đồn"},
      {"districtId":"336","provinceId":"30","name":"Thành phố Đông Hà"},
      {"districtId":"337","provinceId":"30","name":"Thị xã Quảng Trị"},
      {"districtId":"338","provinceId":"30","name":"Huyện Vĩnh Linh"},
      {"districtId":"339","provinceId":"30","name":"Huyện Hướng Hóa"},
      {"districtId":"340","provinceId":"30","name":"Huyện Gio Linh"},
      {"districtId":"341","provinceId":"30","name":"Huyện Đa Krông"},
      {"districtId":"342","provinceId":"30","name":"Huyện Cam Lộ"},
      {"districtId":"343","provinceId":"30","name":"Huyện Triệu Phong"},
      {"districtId":"344","provinceId":"30","name":"Huyện Hải Lăng"},
      {"districtId":"345","provinceId":"30","name":"Huyện Cồn Cỏ"},
      {"districtId":"346","provinceId":"31","name":"Thành phố Huế"},
      {"districtId":"347","provinceId":"31","name":"Huyện Phong Điền"},
      {"districtId":"348","provinceId":"31","name":"Huyện Quảng Điền"},
      {"districtId":"349","provinceId":"31","name":"Huyện Phú Vang"},
      {"districtId":"350","provinceId":"31","name":"Thị xã Hương Thủy"},
      {"districtId":"351","provinceId":"31","name":"Thị xã Hương Trà"},
      {"districtId":"352","provinceId":"31","name":"Huyện A Lưới"},
      {"districtId":"353","provinceId":"31","name":"Huyện Phú Lộc"},
      {"districtId":"354","provinceId":"31","name":"Huyện Nam Đông"},
      {"districtId":"355","provinceId":"32","name":"Quận Liên Chiểu"},
      {"districtId":"356","provinceId":"32","name":"Quận Thanh Khê"},
      {"districtId":"357","provinceId":"32","name":"Quận Hải Châu"},
      {"districtId":"358","provinceId":"32","name":"Quận Sơn Trà"},
      {"districtId":"359","provinceId":"32","name":"Quận Ngũ Hành Sơn"},
      {"districtId":"360","provinceId":"32","name":"Quận Cẩm Lệ"},
      {"districtId":"361","provinceId":"32","name":"Huyện Hòa Vang"},
      {"districtId":"362","provinceId":"32","name":"Huyện Hoàng Sa"},
      {"districtId":"363","provinceId":"33","name":"Thành phố Tam Kỳ"},
      {"districtId":"364","provinceId":"33","name":"Thành phố Hội An"},
      {"districtId":"365","provinceId":"33","name":"Huyện Tây Giang"},
      {"districtId":"366","provinceId":"33","name":"Huyện Đông Giang"},
      {"districtId":"367","provinceId":"33","name":"Huyện Đại Lộc"},
      {"districtId":"368","provinceId":"33","name":"Thị xã Điện Bàn"},
      {"districtId":"369","provinceId":"33","name":"Huyện Duy Xuyên"},
      {"districtId":"370","provinceId":"33","name":"Huyện Quế Sơn"},
      {"districtId":"371","provinceId":"33","name":"Huyện Nam Giang"},
      {"districtId":"372","provinceId":"33","name":"Huyện Phước Sơn"},
      {"districtId":"373","provinceId":"33","name":"Huyện Hiệp Đức"},
      {"districtId":"374","provinceId":"33","name":"Huyện Thăng Bình"},
      {"districtId":"375","provinceId":"33","name":"Huyện Tiên Phước"},
      {"districtId":"376","provinceId":"33","name":"Huyện Bắc Trà My"},
      {"districtId":"377","provinceId":"33","name":"Huyện Nam Trà My"},
      {"districtId":"378","provinceId":"33","name":"Huyện Núi Thành"},
      {"districtId":"379","provinceId":"33","name":"Huyện Phú Ninh"},
      {"districtId":"380","provinceId":"33","name":"Huyện Nông Sơn"},
      {"districtId":"381","provinceId":"34","name":"Thành phố Quảng Ngãi"},
      {"districtId":"382","provinceId":"34","name":"Huyện Bình Sơn"},
      {"districtId":"383","provinceId":"34","name":"Huyện Trà Bồng"},
      {"districtId":"384","provinceId":"34","name":"Huyện Sơn Tịnh"},
      {"districtId":"385","provinceId":"34","name":"Huyện Tư Nghĩa"},
      {"districtId":"386","provinceId":"34","name":"Huyện Sơn Hà"},
      {"districtId":"387","provinceId":"34","name":"Huyện Sơn Tây"},
      {"districtId":"388","provinceId":"34","name":"Huyện Minh Long"},
      {"districtId":"389","provinceId":"34","name":"Huyện Nghĩa Hành"},
      {"districtId":"390","provinceId":"34","name":"Huyện Mộ Đức"},
      {"districtId":"391","provinceId":"34","name":"Thị xã Đức Phổ"},
      {"districtId":"392","provinceId":"34","name":"Huyện Ba Tơ"},
      {"districtId":"393","provinceId":"34","name":"Huyện Lý Sơn"},
      {"districtId":"394","provinceId":"35","name":"Thành phố Quy Nhơn"},
      {"districtId":"395","provinceId":"35","name":"Huyện An Lão"},
      {"districtId":"396","provinceId":"35","name":"Thị xã Hoài Nhơn"},
      {"districtId":"397","provinceId":"35","name":"Huyện Hoài Ân"},
      {"districtId":"398","provinceId":"35","name":"Huyện Phù Mỹ"},
      {"districtId":"399","provinceId":"35","name":"Huyện Vĩnh Thạnh"},
      {"districtId":"400","provinceId":"35","name":"Huyện Tây Sơn"},
      {"districtId":"401","provinceId":"35","name":"Huyện Phù Cát"},
      {"districtId":"402","provinceId":"35","name":"Thị xã An Nhơn"},
      {"districtId":"403","provinceId":"35","name":"Huyện Tuy Phước"},
      {"districtId":"404","provinceId":"35","name":"Huyện Vân Canh"},
      {"districtId":"405","provinceId":"36","name":"Thành phố Tuy Hoà"},
      {"districtId":"406","provinceId":"36","name":"Thị xã Sông Cầu"},
      {"districtId":"407","provinceId":"36","name":"Huyện Đồng Xuân"},
      {"districtId":"408","provinceId":"36","name":"Huyện Tuy An"},
      {"districtId":"409","provinceId":"36","name":"Huyện Sơn Hòa"},
      {"districtId":"410","provinceId":"36","name":"Huyện Sông Hinh"},
      {"districtId":"411","provinceId":"36","name":"Huyện Tây Hoà"},
      {"districtId":"412","provinceId":"36","name":"Huyện Phú Hoà"},
      {"districtId":"413","provinceId":"36","name":"Thị xã Đông Hòa"},
      {"districtId":"414","provinceId":"37","name":"Thành phố Nha Trang"},
      {"districtId":"415","provinceId":"37","name":"Thành phố Cam Ranh"},
      {"districtId":"416","provinceId":"37","name":"Huyện Cam Lâm"},
      {"districtId":"417","provinceId":"37","name":"Huyện Vạn Ninh"},
      {"districtId":"418","provinceId":"37","name":"Thị xã Ninh Hòa"},
      {"districtId":"419","provinceId":"37","name":"Huyện Khánh Vĩnh"},
      {"districtId":"420","provinceId":"37","name":"Huyện Diên Khánh"},
      {"districtId":"421","provinceId":"37","name":"Huyện Khánh Sơn"},
      {"districtId":"422","provinceId":"37","name":"Huyện Trường Sa"},
      {"districtId":"423","provinceId":"38","name":"Thành phố Phan Rang-Tháp Chàm"},
      {"districtId":"424","provinceId":"38","name":"Huyện Bác Ái"},
      {"districtId":"425","provinceId":"38","name":"Huyện Ninh Sơn"},
      {"districtId":"426","provinceId":"38","name":"Huyện Ninh Hải"},
      {"districtId":"427","provinceId":"38","name":"Huyện Ninh Phước"},
      {"districtId":"428","provinceId":"38","name":"Huyện Thuận Bắc"},
      {"districtId":"429","provinceId":"38","name":"Huyện Thuận Nam"},
      {"districtId":"430","provinceId":"39","name":"Thành phố Phan Thiết"},
      {"districtId":"431","provinceId":"39","name":"Thị xã La Gi"},
      {"districtId":"432","provinceId":"39","name":"Huyện Tuy Phong"},
      {"districtId":"433","provinceId":"39","name":"Huyện Bắc Bình"},
      {"districtId":"434","provinceId":"39","name":"Huyện Hàm Thuận Bắc"},
      {"districtId":"435","provinceId":"39","name":"Huyện Hàm Thuận Nam"},
      {"districtId":"436","provinceId":"39","name":"Huyện Tánh Linh"},
      {"districtId":"437","provinceId":"39","name":"Huyện Đức Linh"},
      {"districtId":"438","provinceId":"39","name":"Huyện Hàm Tân"},
      {"districtId":"439","provinceId":"39","name":"Huyện Phú Quí"},
      {"districtId":"440","provinceId":"40","name":"Thành phố Kon Tum"},
      {"districtId":"441","provinceId":"40","name":"Huyện Đắk Glei"},
      {"districtId":"442","provinceId":"40","name":"Huyện Ngọc Hồi"},
      {"districtId":"443","provinceId":"40","name":"Huyện Đắk Tô"},
      {"districtId":"444","provinceId":"40","name":"Huyện Kon Plông"},
      {"districtId":"445","provinceId":"40","name":"Huyện Kon Rẫy"},
      {"districtId":"446","provinceId":"40","name":"Huyện Đắk Hà"},
      {"districtId":"447","provinceId":"40","name":"Huyện Sa Thầy"},
      {"districtId":"448","provinceId":"40","name":"Huyện Tu Mơ Rông"},
      {"districtId":"449","provinceId":"40","name":"Huyện Ia H' Drai"},
      {"districtId":"450","provinceId":"41","name":"Thành phố Pleiku"},
      {"districtId":"451","provinceId":"41","name":"Thị xã An Khê"},
      {"districtId":"452","provinceId":"41","name":"Thị xã Ayun Pa"},
      {"districtId":"453","provinceId":"41","name":"Huyện KBang"},
      {"districtId":"454","provinceId":"41","name":"Huyện Đăk Đoa"},
      {"districtId":"455","provinceId":"41","name":"Huyện Chư Păh"},
      {"districtId":"456","provinceId":"41","name":"Huyện Ia Grai"},
      {"districtId":"457","provinceId":"41","name":"Huyện Mang Yang"},
      {"districtId":"458","provinceId":"41","name":"Huyện Kông Chro"},
      {"districtId":"459","provinceId":"41","name":"Huyện Đức Cơ"},
      {"districtId":"460","provinceId":"41","name":"Huyện Chư Prông"},
      {"districtId":"461","provinceId":"41","name":"Huyện Chư Sê"},
      {"districtId":"462","provinceId":"41","name":"Huyện Đăk Pơ"},
      {"districtId":"463","provinceId":"41","name":"Huyện Ia Pa"},
      {"districtId":"464","provinceId":"41","name":"Huyện Krông Pa"},
      {"districtId":"465","provinceId":"41","name":"Huyện Phú Thiện"},
      {"districtId":"466","provinceId":"41","name":"Huyện Chư Pưh"},
      {"districtId":"467","provinceId":"42","name":"Thành phố Buôn Ma Thuột"},
      {"districtId":"468","provinceId":"42","name":"Thị Xã Buôn Hồ"},
      {"districtId":"469","provinceId":"42","name":"Huyện Ea H'leo"},
      {"districtId":"470","provinceId":"42","name":"Huyện Ea Súp"},
      {"districtId":"471","provinceId":"42","name":"Huyện Buôn Đôn"},
      {"districtId":"472","provinceId":"42","name":"Huyện Cư M'gar"},
      {"districtId":"473","provinceId":"42","name":"Huyện Krông Búk"},
      {"districtId":"474","provinceId":"42","name":"Huyện Krông Năng"},
      {"districtId":"475","provinceId":"42","name":"Huyện Ea Kar"},
      {"districtId":"476","provinceId":"42","name":"Huyện M'Đrắk"},
      {"districtId":"477","provinceId":"42","name":"Huyện Krông Bông"},
      {"districtId":"478","provinceId":"42","name":"Huyện Krông Pắc"},
      {"districtId":"479","provinceId":"42","name":"Huyện Krông A Na"},
      {"districtId":"480","provinceId":"42","name":"Huyện Lắk"},
      {"districtId":"481","provinceId":"42","name":"Huyện Cư Kuin"},
      {"districtId":"482","provinceId":"43","name":"Thành phố Gia Nghĩa"},
      {"districtId":"483","provinceId":"43","name":"Huyện Đăk Glong"},
      {"districtId":"484","provinceId":"43","name":"Huyện Cư Jút"},
      {"districtId":"485","provinceId":"43","name":"Huyện Đắk Mil"},
      {"districtId":"486","provinceId":"43","name":"Huyện Krông Nô"},
      {"districtId":"487","provinceId":"43","name":"Huyện Đắk Song"},
      {"districtId":"488","provinceId":"43","name":"Huyện Đắk R'Lấp"},
      {"districtId":"489","provinceId":"43","name":"Huyện Tuy Đức"},
      {"districtId":"490","provinceId":"44","name":"Thành phố Đà Lạt"},
      {"districtId":"491","provinceId":"44","name":"Thành phố Bảo Lộc"},
      {"districtId":"492","provinceId":"44","name":"Huyện Đam Rông"},
      {"districtId":"493","provinceId":"44","name":"Huyện Lạc Dương"},
      {"districtId":"494","provinceId":"44","name":"Huyện Lâm Hà"},
      {"districtId":"495","provinceId":"44","name":"Huyện Đơn Dương"},
      {"districtId":"496","provinceId":"44","name":"Huyện Đức Trọng"},
      {"districtId":"497","provinceId":"44","name":"Huyện Di Linh"},
      {"districtId":"498","provinceId":"44","name":"Huyện Bảo Lâm"},
      {"districtId":"499","provinceId":"44","name":"Huyện Đạ Huoai"},
      {"districtId":"500","provinceId":"44","name":"Huyện Đạ Tẻh"},
      {"districtId":"501","provinceId":"44","name":"Huyện Cát Tiên"},
      {"districtId":"502","provinceId":"45","name":"Thị xã Phước Long"},
      {"districtId":"503","provinceId":"45","name":"Thành phố Đồng Xoài"},
      {"districtId":"504","provinceId":"45","name":"Thị xã Bình Long"},
      {"districtId":"505","provinceId":"45","name":"Huyện Bù Gia Mập"},
      {"districtId":"506","provinceId":"45","name":"Huyện Lộc Ninh"},
      {"districtId":"507","provinceId":"45","name":"Huyện Bù Đốp"},
      {"districtId":"508","provinceId":"45","name":"Huyện Hớn Quản"},
      {"districtId":"509","provinceId":"45","name":"Huyện Đồng Phú"},
      {"districtId":"510","provinceId":"45","name":"Huyện Bù Đăng"},
      {"districtId":"511","provinceId":"45","name":"Huyện Chơn Thành"},
      {"districtId":"512","provinceId":"45","name":"Huyện Phú Riềng"},
      {"districtId":"513","provinceId":"46","name":"Thành phố Tây Ninh"},
      {"districtId":"514","provinceId":"46","name":"Huyện Tân Biên"},
      {"districtId":"515","provinceId":"46","name":"Huyện Tân Châu"},
      {"districtId":"516","provinceId":"46","name":"Huyện Dương Minh Châu"},
      {"districtId":"517","provinceId":"46","name":"Huyện Châu Thành"},
      {"districtId":"518","provinceId":"46","name":"Thị xã Hòa Thành"},
      {"districtId":"519","provinceId":"46","name":"Huyện Gò Dầu"},
      {"districtId":"520","provinceId":"46","name":"Huyện Bến Cầu"},
      {"districtId":"521","provinceId":"46","name":"Thị xã Trảng Bàng"},
      {"districtId":"522","provinceId":"47","name":"Thành phố Thủ Dầu Một"},
      {"districtId":"523","provinceId":"47","name":"Huyện Bàu Bàng"},
      {"districtId":"524","provinceId":"47","name":"Huyện Dầu Tiếng"},
      {"districtId":"525","provinceId":"47","name":"Thị xã Bến Cát"},
      {"districtId":"526","provinceId":"47","name":"Huyện Phú Giáo"},
      {"districtId":"527","provinceId":"47","name":"Thị xã Tân Uyên"},
      {"districtId":"528","provinceId":"47","name":"Thành phố Dĩ An"},
      {"districtId":"529","provinceId":"47","name":"Thành phố Thuận An"},
      {"districtId":"530","provinceId":"47","name":"Huyện Bắc Tân Uyên"},
      {"districtId":"531","provinceId":"48","name":"Thành phố Biên Hòa"},
      {"districtId":"532","provinceId":"48","name":"Thành phố Long Khánh"},
      {"districtId":"533","provinceId":"48","name":"Huyện Tân Phú"},
      {"districtId":"534","provinceId":"48","name":"Huyện Vĩnh Cửu"},
      {"districtId":"535","provinceId":"48","name":"Huyện Định Quán"},
      {"districtId":"536","provinceId":"48","name":"Huyện Trảng Bom"},
      {"districtId":"537","provinceId":"48","name":"Huyện Thống Nhất"},
      {"districtId":"538","provinceId":"48","name":"Huyện Cẩm Mỹ"},
      {"districtId":"539","provinceId":"48","name":"Huyện Long Thành"},
      {"districtId":"540","provinceId":"48","name":"Huyện Xuân Lộc"},
      {"districtId":"541","provinceId":"48","name":"Huyện Nhơn Trạch"},
      {"districtId":"542","provinceId":"49","name":"Thành phố Vũng Tàu"},
      {"districtId":"543","provinceId":"49","name":"Thành phố Bà Rịa"},
      {"districtId":"544","provinceId":"49","name":"Huyện Châu Đức"},
      {"districtId":"545","provinceId":"49","name":"Huyện Xuyên Mộc"},
      {"districtId":"546","provinceId":"49","name":"Huyện Long Điền"},
      {"districtId":"547","provinceId":"49","name":"Huyện Đất Đỏ"},
      {"districtId":"548","provinceId":"49","name":"Thị xã Phú Mỹ"},
      {"districtId":"549","provinceId":"49","name":"Huyện Côn Đảo"},
      {"districtId":"550","provinceId":"50","name":"Quận 1"},
      {"districtId":"551","provinceId":"50","name":"Quận 12"},
      {"districtId":"552","provinceId":"50","name":"Quận Gò Vấp"},
      {"districtId":"553","provinceId":"50","name":"Quận Bình Thạnh"},
      {"districtId":"554","provinceId":"50","name":"Quận Tân Bình"},
      {"districtId":"555","provinceId":"50","name":"Quận Tân Phú"},
      {"districtId":"556","provinceId":"50","name":"Quận Phú Nhuận"},
      {"districtId":"557","provinceId":"50","name":"Thành phố Thủ Đức"},
      {"districtId":"558","provinceId":"50","name":"Quận 3"},
      {"districtId":"559","provinceId":"50","name":"Quận 10"},
      {"districtId":"560","provinceId":"50","name":"Quận 11"},
      {"districtId":"561","provinceId":"50","name":"Quận 4"},
      {"districtId":"562","provinceId":"50","name":"Quận 5"},
      {"districtId":"563","provinceId":"50","name":"Quận 6"},
      {"districtId":"564","provinceId":"50","name":"Quận 8"},
      {"districtId":"565","provinceId":"50","name":"Quận Bình Tân"},
      {"districtId":"566","provinceId":"50","name":"Quận 7"},
      {"districtId":"567","provinceId":"50","name":"Huyện Củ Chi"},
      {"districtId":"568","provinceId":"50","name":"Huyện Hóc Môn"},
      {"districtId":"569","provinceId":"50","name":"Huyện Bình Chánh"},
      {"districtId":"570","provinceId":"50","name":"Huyện Nhà Bè"},
      {"districtId":"571","provinceId":"50","name":"Huyện Cần Giờ"},
      {"districtId":"572","provinceId":"51","name":"Thành phố Tân An"},
      {"districtId":"573","provinceId":"51","name":"Thị xã Kiến Tường"},
      {"districtId":"574","provinceId":"51","name":"Huyện Tân Hưng"},
      {"districtId":"575","provinceId":"51","name":"Huyện Vĩnh Hưng"},
      {"districtId":"576","provinceId":"51","name":"Huyện Mộc Hóa"},
      {"districtId":"577","provinceId":"51","name":"Huyện Tân Thạnh"},
      {"districtId":"578","provinceId":"51","name":"Huyện Thạnh Hóa"},
      {"districtId":"579","provinceId":"51","name":"Huyện Đức Huệ"},
      {"districtId":"580","provinceId":"51","name":"Huyện Đức Hòa"},
      {"districtId":"581","provinceId":"51","name":"Huyện Bến Lức"},
      {"districtId":"582","provinceId":"51","name":"Huyện Thủ Thừa"},
      {"districtId":"583","provinceId":"51","name":"Huyện Tân Trụ"},
      {"districtId":"584","provinceId":"51","name":"Huyện Cần Đước"},
      {"districtId":"585","provinceId":"51","name":"Huyện Cần Giuộc"},
      {"districtId":"586","provinceId":"51","name":"Huyện Châu Thành"},
      {"districtId":"587","provinceId":"52","name":"Thành phố Mỹ Tho"},
      {"districtId":"588","provinceId":"52","name":"Thị xã Gò Công"},
      {"districtId":"589","provinceId":"52","name":"Thị xã Cai Lậy"},
      {"districtId":"590","provinceId":"52","name":"Huyện Tân Phước"},
      {"districtId":"591","provinceId":"52","name":"Huyện Cái Bè"},
      {"districtId":"592","provinceId":"52","name":"Huyện Cai Lậy"},
      {"districtId":"593","provinceId":"52","name":"Huyện Châu Thành"},
      {"districtId":"594","provinceId":"52","name":"Huyện Chợ Gạo"},
      {"districtId":"595","provinceId":"52","name":"Huyện Gò Công Tây"},
      {"districtId":"596","provinceId":"52","name":"Huyện Gò Công Đông"},
      {"districtId":"597","provinceId":"52","name":"Huyện Tân Phú Đông"},
      {"districtId":"598","provinceId":"53","name":"Thành phố Bến Tre"},
      {"districtId":"599","provinceId":"53","name":"Huyện Châu Thành"},
      {"districtId":"600","provinceId":"53","name":"Huyện Chợ Lách"},
      {"districtId":"601","provinceId":"53","name":"Huyện Mỏ Cày Nam"},
      {"districtId":"602","provinceId":"53","name":"Huyện Giồng Trôm"},
      {"districtId":"603","provinceId":"53","name":"Huyện Bình Đại"},
      {"districtId":"604","provinceId":"53","name":"Huyện Ba Tri"},
      {"districtId":"605","provinceId":"53","name":"Huyện Thạnh Phú"},
      {"districtId":"606","provinceId":"53","name":"Huyện Mỏ Cày Bắc"},
      {"districtId":"607","provinceId":"54","name":"Thành phố Trà Vinh"},
      {"districtId":"608","provinceId":"54","name":"Huyện Càng Long"},
      {"districtId":"609","provinceId":"54","name":"Huyện Cầu Kè"},
      {"districtId":"610","provinceId":"54","name":"Huyện Tiểu Cần"},
      {"districtId":"611","provinceId":"54","name":"Huyện Châu Thành"},
      {"districtId":"612","provinceId":"54","name":"Huyện Cầu Ngang"},
      {"districtId":"613","provinceId":"54","name":"Huyện Trà Cú"},
      {"districtId":"614","provinceId":"54","name":"Huyện Duyên Hải"},
      {"districtId":"615","provinceId":"54","name":"Thị xã Duyên Hải"},
      {"districtId":"616","provinceId":"55","name":"Thành phố Vĩnh Long"},
      {"districtId":"617","provinceId":"55","name":"Huyện Long Hồ"},
      {"districtId":"618","provinceId":"55","name":"Huyện Mang Thít"},
      {"districtId":"619","provinceId":"55","name":"Huyện  Vũng Liêm"},
      {"districtId":"620","provinceId":"55","name":"Huyện Tam Bình"},
      {"districtId":"621","provinceId":"55","name":"Thị xã Bình Minh"},
      {"districtId":"622","provinceId":"55","name":"Huyện Trà Ôn"},
      {"districtId":"623","provinceId":"55","name":"Huyện Bình Tân"},
      {"districtId":"624","provinceId":"56","name":"Thành phố Cao Lãnh"},
      {"districtId":"625","provinceId":"56","name":"Thành phố Sa Đéc"},
      {"districtId":"626","provinceId":"56","name":"Thành phố Hồng Ngự"},
      {"districtId":"627","provinceId":"56","name":"Huyện Tân Hồng"},
      {"districtId":"628","provinceId":"56","name":"Huyện Hồng Ngự"},
      {"districtId":"629","provinceId":"56","name":"Huyện Tam Nông"},
      {"districtId":"630","provinceId":"56","name":"Huyện Tháp Mười"},
      {"districtId":"631","provinceId":"56","name":"Huyện Cao Lãnh"},
      {"districtId":"632","provinceId":"56","name":"Huyện Thanh Bình"},
      {"districtId":"633","provinceId":"56","name":"Huyện Lấp Vò"},
      {"districtId":"634","provinceId":"56","name":"Huyện Lai Vung"},
      {"districtId":"635","provinceId":"56","name":"Huyện Châu Thành"},
      {"districtId":"636","provinceId":"57","name":"Thành phố Long Xuyên"},
      {"districtId":"637","provinceId":"57","name":"Thành phố Châu Đốc"},
      {"districtId":"638","provinceId":"57","name":"Huyện An Phú"},
      {"districtId":"639","provinceId":"57","name":"Thị xã Tân Châu"},
      {"districtId":"640","provinceId":"57","name":"Huyện Phú Tân"},
      {"districtId":"641","provinceId":"57","name":"Huyện Châu Phú"},
      {"districtId":"642","provinceId":"57","name":"Huyện Tịnh Biên"},
      {"districtId":"643","provinceId":"57","name":"Huyện Tri Tôn"},
      {"districtId":"644","provinceId":"57","name":"Huyện Châu Thành"},
      {"districtId":"645","provinceId":"57","name":"Huyện Chợ Mới"},
      {"districtId":"646","provinceId":"57","name":"Huyện Thoại Sơn"},
      {"districtId":"647","provinceId":"58","name":"Thành phố Rạch Giá"},
      {"districtId":"648","provinceId":"58","name":"Thành phố Hà Tiên"},
      {"districtId":"649","provinceId":"58","name":"Huyện Kiên Lương"},
      {"districtId":"650","provinceId":"58","name":"Huyện Hòn Đất"},
      {"districtId":"651","provinceId":"58","name":"Huyện Tân Hiệp"},
      {"districtId":"652","provinceId":"58","name":"Huyện Châu Thành"},
      {"districtId":"653","provinceId":"58","name":"Huyện Giồng Riềng"},
      {"districtId":"654","provinceId":"58","name":"Huyện Gò Quao"},
      {"districtId":"655","provinceId":"58","name":"Huyện An Biên"},
      {"districtId":"656","provinceId":"58","name":"Huyện An Minh"},
      {"districtId":"657","provinceId":"58","name":"Huyện Vĩnh Thuận"},
      {"districtId":"658","provinceId":"58","name":"Thành phố Phú Quốc"},
      {"districtId":"659","provinceId":"58","name":"Huyện Kiên Hải"},
      {"districtId":"660","provinceId":"58","name":"Huyện U Minh Thượng"},
      {"districtId":"661","provinceId":"58","name":"Huyện Giang Thành"},
      {"districtId":"662","provinceId":"59","name":"Quận Ninh Kiều"},
      {"districtId":"663","provinceId":"59","name":"Quận Ô Môn"},
      {"districtId":"664","provinceId":"59","name":"Quận Bình Thuỷ"},
      {"districtId":"665","provinceId":"59","name":"Quận Cái Răng"},
      {"districtId":"666","provinceId":"59","name":"Quận Thốt Nốt"},
      {"districtId":"667","provinceId":"59","name":"Huyện Vĩnh Thạnh"},
      {"districtId":"668","provinceId":"59","name":"Huyện Cờ Đỏ"},
      {"districtId":"669","provinceId":"59","name":"Huyện Phong Điền"},
      {"districtId":"670","provinceId":"59","name":"Huyện Thới Lai"},
      {"districtId":"671","provinceId":"60","name":"Thành phố Vị Thanh"},
      {"districtId":"672","provinceId":"60","name":"Thành phố Ngã Bảy"},
      {"districtId":"673","provinceId":"60","name":"Huyện Châu Thành A"},
      {"districtId":"674","provinceId":"60","name":"Huyện Châu Thành"},
      {"districtId":"675","provinceId":"60","name":"Huyện Phụng Hiệp"},
      {"districtId":"676","provinceId":"60","name":"Huyện Vị Thuỷ"},
      {"districtId":"677","provinceId":"60","name":"Huyện Long Mỹ"},
      {"districtId":"678","provinceId":"60","name":"Thị xã Long Mỹ"},
      {"districtId":"679","provinceId":"61","name":"Thành phố Sóc Trăng"},
      {"districtId":"680","provinceId":"61","name":"Huyện Châu Thành"},
      {"districtId":"681","provinceId":"61","name":"Huyện Kế Sách"},
      {"districtId":"682","provinceId":"61","name":"Huyện Mỹ Tú"},
      {"districtId":"683","provinceId":"61","name":"Huyện Cù Lao Dung"},
      {"districtId":"684","provinceId":"61","name":"Huyện Long Phú"},
      {"districtId":"685","provinceId":"61","name":"Huyện Mỹ Xuyên"},
      {"districtId":"686","provinceId":"61","name":"Thị xã Ngã Năm"},
      {"districtId":"687","provinceId":"61","name":"Huyện Thạnh Trị"},
      {"districtId":"688","provinceId":"61","name":"Thị xã Vĩnh Châu"},
      {"districtId":"689","provinceId":"61","name":"Huyện Trần Đề"},
      {"districtId":"690","provinceId":"62","name":"Thành phố Bạc Liêu"},
      {"districtId":"691","provinceId":"62","name":"Huyện Hồng Dân"},
      {"districtId":"692","provinceId":"62","name":"Huyện Phước Long"},
      {"districtId":"693","provinceId":"62","name":"Huyện Vĩnh Lợi"},
      {"districtId":"694","provinceId":"62","name":"Thị xã Giá Rai"},
      {"districtId":"695","provinceId":"62","name":"Huyện Đông Hải"},
      {"districtId":"696","provinceId":"62","name":"Huyện Hoà Bình"},
      {"districtId":"697","provinceId":"63","name":"Thành phố Cà Mau"},
      {"districtId":"698","provinceId":"63","name":"Huyện U Minh"},
      {"districtId":"699","provinceId":"63","name":"Huyện Thới Bình"},
      {"districtId":"700","provinceId":"63","name":"Huyện Trần Văn Thời"},
      {"districtId":"701","provinceId":"63","name":"Huyện Cái Nước"},
      {"districtId":"702","provinceId":"63","name":"Huyện Đầm Dơi"},
      {"districtId":"703","provinceId":"63","name":"Huyện Năm Căn"},
      {"districtId":"704","provinceId":"63","name":"Huyện Phú Tân"},
      {"districtId":"705","provinceId":"63","name":"Huyện Ngọc Hiển"}
    ])
  }
}
